name:                nubot
version:             0.1.0.0
github:              "nutr1t07/nubot"
license:             BSD3
author:              "Nutr1t07"
maintainer:          "nutr1t07@outlook.com"
copyright:           "2021 Nutr1t07"

dependencies:
- base >= 4.7 && < 5
- websockets
- bytestring
- text
- time

- random
- serialise
- aeson

- wreq
- lens

- stringsearch
- utf8-string
- network-uri

- mime-mail
- smtp-mail
- sqlite-simple

- turtle
- base64
- directory

library:
  source-dirs: src

executables:
  nubot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nubot
    when:
    - condition: false
      other-modules: Paths_nubot

tests:
  nubot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nubot
    when:
    - condition: false
      other-modules: Paths_nubot
