name:                nubot
version:             0.1.0.0
github:              "nutr1t07/nubot"
license:             BSD3
author:              "Nutr1t07"
maintainer:          "nutr1t07@outlook.com"
copyright:           "2021 Nutr1t07"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nutr1t07/nubot#readme>

dependencies:
- base >= 4.7 && < 5
- websockets
- bytestring
- text
- time

- random
- serialise
- aeson

- wreq
- lens

- stringsearch
- utf8-string
- network-uri

- mime-mail
- smtp-mail
- sqlite-simple
# - process

library:
  source-dirs: src

executables:
  nubot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nubot
    when:
    - condition: false
      # other-modules: Paths_nubot

tests:
  nubot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nubot
    when:
    - condition: false
      # other-modules: Paths_nubot
